version: '3'
services:
  stunnel:
    container_name: stunnel_server
    build:
      context: .
      dockerfile: ./stunnel_server/Dockerfile
    networks:
      bridge:
        ipv4_address: 192.168.48.3
    ports:
      - "8088:8088"
    volumes:
      - ./configs/stunnel.conf:/etc/opt/cprocsp/stunnel/stunnel.conf
      - ./configs/:/etc/stunnel/
      - ./keys/:/keys/

networks:
  bridge:
    ipam:
      driver: default
      config:
        - subnet: 192.168.48.0/24