version: '3'
services:
  stunnel:
    container_name: stunnel_server
    build:
      context: .
      dockerfile: ./stunnel_server/Dockerfile
    networks:
      bridge:
        ipv4_address: 192.168.48.3
    ports:
      - "443:443"
    volumes:
      - ./configs/stunnel.conf:/etc/stunnel/stunnel.conf
    depends_on:
      - content

  content:
    container_name: content_server
    build:
      context: .
      dockerfile: ./content_server/Dockerfile
    networks:
      bridge:
        ipv4_address: 192.168.48.4

networks:
  bridge:
    ipam:
      driver: default
      config:
        - subnet: 192.168.48.0/24