version: '3'
services:
  stunnel:
    container_name: server
    build:
      context: .
      dockerfile: /server/Dockerfile
    networks:
      bridge:
        ipv4_address: 192.168.48.3
    ports:
      - "443:443"
    volumes:
      - ./configs/stunnel.conf:/etc/stunnel/stunnel.conf

networks:
  bridge:
    ipam:
      driver: default
      config:
        - subnet: 192.168.48.0/24