version: '3'

services:
  nginx-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    image: nginx:client
    container_name: client
    networks:
      - bridge
    depends_on:
      - nginx-server
    ports:
      - "85:85"

  nginx-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: nginx:server
    container_name: server
    networks:
      - bridge

networks:
  bridge:
