socket=l:TCP_NODELAY=1
socket=r:TCP_NODELAY=1
pid = /etc/stunnel/stunnel.pid
output = /etc/stunnel/stunnel.log
debug = 7
[https]
accept=0.0.0.0:8088
connect=int44-ttls-cert.zakupki.gov.ru:443
cert = /etc/stunnel/client.cer
client = yes
verify=2